### ISSUE TITLE
Warnings/error on start up

### ISSUE THREAD

**Issue by Chaz6** [wollomatic/torrelay#1]
Using the example configuration, I see a couple of warnings and an error logged:-

```
tor-relay    | Oct 28 20:25:29.182 [warn] Error creating directory /var/lib/tor/.tor: Permission denied
tor-relay    | Oct 28 20:25:29.182 [notice] Closing partially-constructed OR listener connection (ready) on 0.0.0.0:9001
tor-relay    | Oct 28 20:25:29.182 [notice] Closing partially-constructed OR listener connection (ready) on [::]:9001
tor-relay    | Oct 28 20:25:29.182 [warn] Failed to parse/validate config: Couldn't create private data directory "/var/lib/tor/.tor"
tor-relay    | Oct 28 20:25:29.182 [err] Reading config failed--see warnings above.
```

Is this anything to be concerned about?

The host is running Debian 12 Bookworm, kernel `6.1.0-13-amd64` and Docker CE `5:24.0.7-1~debian.12~bookworm`.

**Comment by wollomatic** [comment]
Hello Chaz6,

seems like there is a problem with the mounted data directory in your configuraton:

docker compose should have created a volume called data. But in this case it looks for me that data data is mounted as a bind mount. (If you did this intentionally, you need to set the directory owner to uid 101). Could you please check if a docker volume was created? ``docker volume ls`` should list all created volumes.

It also looks like that the torrc may not be mounted in the container.

**Comment by wollomatic** [comment]
I tested it on a fresh server and could not reproduce the behaviour.

Docker Engine 24.0.7
Docker Compose version v2.21.0

**Comment by Chaz6** [comment]
I did mount data as a volume, but even without changing the uid, I did observe that it created data/.tor with uid 101. It seems to be working fine now, thanks!
