### ISSUE TITLE
Update to 0.4.8.8

### ISSUE THREAD

**Issue by Chaz6** [wollomatic/torrelay#2]
There is a remote-triggered crash bug in 0.4.8.7. Please see https://forum.torproject.org/t/tor-relays-please-upgrade-to-new-tor-release-0-4-7-16-or-0-4-8-8-asap/10065

**Comment by wollomatic** [comment]
Thanks for reporting this issue. I will update the repository as soon as the upstream Debian repository is updated.

**Comment by wollomatic** [comment]
Updated: https://github.com/wollomatic/torrelay/commit/db28f1a2953bc1ea37c4049df13d27d341e222aa
Thanks again @Chaz6
